### ISSUE TITLE
AttributeError: 'Route' object has no attribute 'trip_set'

### ISSUE THREAD

**Issue by derickl** [gtfscreator/gtfs-server#16]
Hi All,

I've attempted to import a GTFS feed and get the above error. I'm fairly new to GTFS and this project in general.

The import process experiences the error when processing the routes.

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/xxxxx/Workspaces/gtfs-server/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/xxxxx/Workspaces/gtfs-server/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/xxxxx/Workspaces/gtfs-server/env/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/xxxxx/Workspaces/gtfs-server/env/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/xxxxx/Workspaces/gtfs-server/gtfsserver/multigtfs/management/commands/importgtfs.py", line 90, in handle
    feed.import_gtfs(gtfs_feed)
  File "/Users/xxxxx/Workspaces/gtfs-server/gtfsserver/multigtfs/models/feed.py", line 143, in import_gtfs
    route.update_geometry()
  File "/Users/xxxxx/Workspaces/gtfs-server/gtfsserver/multigtfs/models/route.py", line 74, in update_geometry
    trips = self.trip_set.exclude(geometry=None)
AttributeError: 'Route' object has no attribute 'trip_set'`

What do I need to modify?

Any help will be highly appreciated.

Thanks

**Comment by derickl** [comment]
Fixed. Will be sending a PR
